import Head from 'next/head';
import { useState } from 'react';
import { Button, Htag, Input, Rating, Skills, Tag, TextArea, Tsize } from '../components';
import { withLayout } from '../layout/Layout';
import axios from 'axios';
import { MenuItem } from '../interfaces/menu.interfaces';
import { GetStaticProps } from 'next';
import { API } from '../helpers/api';

function Home({menu}: HomeProps) : JSX.Element {
  const [rating, setRating] = useState<number>(2);
  return (
    <>
      <Head>
        <title>MyTop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai+Looped:wght@400;600;700&family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      <>
        <Htag tag= 'h1'>Tekst</Htag>
        <Tsize size= 'text_12'>Heading</Tsize>
        <Button color= 'primary' arrow='right'>Heading</Button>
        <Button color= 'ghost' arrow='down'>Heading</Button>
        <Tag color="gray" size='s' href='#'>s</Tag>
        <Tag color="red" size='m' >m</Tag>
        <Rating rating={rating} isEditable setRating={setRating}/>
        <Skills>fdsfdsf</Skills>
        <Skills>fdsfdsf</Skills>
        <Input placeholder='input'/>
        <TextArea placeholder='textarea'/>
      </>
    </>
  );
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<MenuItem[]>(API.topPage.find, {
    firstCategory
  });

  return {
    props: {
      menu, 
      firstCategory
    }
  };
};

interface HomeProps extends Record<string, unknown>{
  menu: MenuItem[];
  firstCategory: number;
}